Repository HCI-Data-Analysis/HCI-data-analysis, pull requests merged in 2021-11, with the labels that each got.

#45 Fix Canvas submission retrieval README
  README.md
Labels: documentation

#35 Fix background survey
  schemas/raw.py
  scripts/anonymize_survey/anonymize_survey.py
  util/encoder.py
Labels: bug

#48 Anonymize module feedback survey
  anon.py
Labels: enhancement

#57 Reading Logs
  README.md
  reading_logs_retrieval.py
  scripts/canvas_reading_logs_retrieval/__init__.py
  scripts/canvas_reading_logs_retrieval/canvas_reading_logs_retrieval.py
  scripts/canvas_submission_retrieval/canvas_submission_retrieval.py
  util/encoder.py
Labels: enhancement

#58 Update canvas_reading_logs_retrieval.py
  scripts/canvas_reading_logs_retrieval/canvas_reading_logs_retrieval.py
Labels: bug

#56 Merge anon.py into anonymize.py
  anon.py
  anonymize.py
Labels: enhancement

#53 Module feedback analysis
  module_feedback_analysis.py
  schemas/__init__.py
  schemas/surveys.py
  scripts/__init__.py
  scripts/analyze_module_feedback_survey/__init__.py
  scripts/analyze_module_feedback_survey/analyze_module_feedback_survey.md
  scripts/analyze_module_feedback_survey/analyze_module_feedback_survey.py
  scripts/clustering/data_preparation_for_clustering.py
  util/__init__.py
  util/data_cleaner.py
Labels: enhancement

#59 Reading Logs
  api/canvas.py
  reading_logs_retrieval.py
  scripts/canvas_reading_logs_retrieval/canvas_reading_logs_retrieval.py
  util/encoder.py
  util/file.py
Labels: enhancement

#61 Format module lecture data and return json output
  data/modules/__init__.py
  parse_module_paragraphs.py
  requirements.txt
  scripts/parse_module_paragraphs/__init__.py
  scripts/parse_module_paragraphs/parse_module_paragraphs.py
Labels: enhancement

#67 Parse paragraph modules
  scripts/parse_module_paragraphs/parse_module_paragraphs.py
Labels: enhancement

#68 Reading logs utils
  .gitignore
  parse_module_paragraphs.py
  schemas/__init__.py
  schemas/course.py
  util/__init__.py
  util/const.py
  util/reading_logs.py
Labels: enhancement

#63 Num paragraphs analysis + reading logs analysis setup
  reading_logs_analysis.py
  scripts/__init__.py
  scripts/reading_logs/__init__.py
  scripts/reading_logs/num_paragraphs_analysis.py
  util/__init__.py
  util/plots.py
Labels: enhancement

#72 Reading Log Utils Fixes
  util/reading_logs.py
Labels: enhancement

#73 Normalize reading speed by difficulty
  util/__init__.py
  util/reading_logs.py
  util/util.py
Labels: enhancement
