Repository HCI-Data-Analysis/HCI-data-analysis, pull requests merged in 2021-09, with the labels that each got.

#1 Overhale of generate_half_key.py and more detailed .md file
  scripts/generate_half_key/generate_half_key.md
  scripts/generate_half_key/generate_half_key.py
Labels: enhancement

#7 Reading log zip file anonymization
  scripts/convert_zip_file/__init__.py
  scripts/convert_zip_file/convert_zip_file_id.md
  scripts/convert_zip_file/convert_zip_file_id.py
  scripts/generate_half_key/generate_half_key.md
Labels: completetion

#5 Scripts for anonymizing surveys and generating keys
  scripts/anonymizer/anaonymizer.md
  scripts/anonymizer/anonymizer.py
  scripts/example/example.md
  scripts/example/example.py
  scripts/key_generator/key_generator.md
  scripts/key_generator/key_generator.py
  scripts/survey_anonymizers/survey_anonymizer.md
  scripts/survey_anonymizers/survey_anonymizer.py
Labels: enhancement

#14 minor fix on read.md for all python scripts
  scripts/convert_gradebook/convert_gradebook.md
  scripts/convert_survey/convert_survey.md
  scripts/convert_ta_survey/convert_ta_survey.md
  scripts/convert_zip_file/convert_zip_file_id.md
  scripts/generate_half_key/generate_half_key.md
Labels: bug

#18 Merged branches
  .gitignore
  README.md
  anonymize.py
  anonymize_web.py
  data/__init__.py
  keys/__init__.py
  requirements.txt
  schemas/__init__.py
  schemas/gradebook.py
  schemas/key.py
  schemas/raw.py
  schemas/surveys.py
  scripts/__init__.py
  scripts/anonymize_gradebook/__init__.py
  scripts/anonymize_gradebook/anonymize_gradebook.md
  scripts/anonymize_gradebook/anonymize_gradebook.py
  scripts/anonymize_survey/__init__.py
  scripts/anonymize_survey/anonymize_survey.md
  scripts/anonymize_survey/anonymize_survey.py
  scripts/anonymize_ta_survey/__init__.py
  scripts/anonymize_ta_survey/anonymize_ta_survey.md
  scripts/anonymize_ta_survey/anonymize_ta_survey.py
  scripts/anonymize_zip_file/__init__.py
  scripts/anonymize_zip_file/anonymize_zip_file.md
  scripts/anonymize_zip_file/anonymize_zip_file.py
  scripts/example/example.md
  scripts/example/example.py
  scripts/generate_key/__init__.py
  scripts/generate_key/generate_key.md
  scripts/generate_key/generate_key.py
  util/__init__.py
  util/data_cleaner.py
  util/decode_base_64.py
  util/encoder.py
  web/anonymizer/anonymized/341_Background_Survey_Header.csv_anonymized.csv
  web/anonymizer/key/data448-key.csv
  web/anonymizer/main.html
  web/anonymizer/temp/341_Background_Survey_Header.csv
  web/anonymizer/temp/key/341_Background_Survey_Header.csv
  web/anonymizer/temp/key/data448-key.csv
Labels: documentation, enhancement
